### PR TITLE
Fix for removal of Ranges deprecation in 0.4

### PR DESCRIPTION
**Pull request by timholy**
This is a good diff to view with `?w=1` appended to the URL (my editor truncated a bunch of end-of-line whitespace).

### CODE REVIEW

**Comment by tlycken** [comment]
OT: doesn't `git rebase --whitespace=fix` solve that for you? That's what I usually do when my editor can't get along with whitespace...

**Comment by timholy** [comment]
In this case, if you view this diff you'll think I changed a lot of lines. But most of those were just whitespace fixes (ones that I didn't even have to make directly); it turns out this file had quite a lot of whitespace problems in its version checked into the repository.

Adding `?w=1` to the end of the URL lets you see the functionally-relevant changes.

**Comment by timholy** [comment]
@Keno, FYI: after you merged this I pushed a new commit d0a70614aa85fcfeb3ed8c84957e4fc9203d0d3b; I just merged that to master myself.

**Comment by timholy** [comment]
Images will be broken until a new version of SIUnits gets tagged; OK if I do that, or do you have some other things you want to include?

**Comment by Keno** [comment]
Go ahead.

**Comment by tlycken** [comment]
@timholy Ah! I misinterpreted you as having truncated `CRLF` to just one of them, or some other nonsense. Just a sign I'd better go home for the day, I guess :P

**Pull request merged**
